### ISSUE TITLE
Reloading in proxy mode looses jspm watcher

### ISSUE THREAD

**Issue by johnraz** [geelen/jspm-server#10]
Whenever I hit refresh in my browser or a reload event is triggered, the JSPM watcher is not started again.

Initial run of `jspm-server --proxy=http://127.0.0.1:8000 --port=8080` , all is fine

```
Navigated to http://127.0.0.1:8080/login/
content_script.js:84 Bind hotkeys 
(index):449 JSPM watching enabled!
main.js:10 I changed
(index):362 Reloaded js/main
```

Hitting refresh in the browser.

```
Navigated to http://127.0.0.1:8080/login/
content_script.js:84 Bind hotkeys 
main.js:8 I changed
```

No more subsequent changes are detected.

**Comment by geelen** [comment]
Wow, ok, not sure what could be causing this. @kevrom, you able to take a look?

**Comment by kevrom** [comment]
Yeh, I'm gonna take a gander in a bit.
