### ISSUE TITLE
Relative jsx reference are not hot-reloaded ?

### ISSUE THREAD

**Issue by johnraz** [geelen/jspm-server#13]
Hi again ! 

This is how I load my main module:

```
<script type="text/javascript">
    System.import('js/main');
</script>
```

Then If I load the `app.jsx` file that lives right next to the `main.js` file like this:

```
import App from 'app.jsx!';
```

Hot reloading fails and I get a full browser refresh instead.

However if I do this:

```
import App from 'js/app.jsx!';
```

All is fine. 

Maybe this is a silly question but I'm trying to wrap my head around this.
Thanks already ;-)

**Comment by geelen** [comment]
Hmm, what happens if you try:

``` js
import App from './app.jsx!`;
```

I assumed you needed the `./` for a relative reference, but maybe you don't...

**Comment by johnraz** [comment]
owkay I was being stupid, it does indeed work as expected with the dot notation. sorry 'bout this one.
