### ISSUE TITLE
change detected but browser is not reloading

### ISSUE THREAD

**Issue by timcash** [geelen/jspm-server#26]
simple project link https://github.com/timcash/jspmtest

OS X 10.10.4
Chrome 44.0.2403.155 (64-bit)
Node v0.12.6

Any ideas why I cannot get the browser to reload when lib/main.js changes? The server logs that it detects the change but the browser does not reload.

**Comment by johnraz** [comment]
The point of this project is precisely that the browser should not reload on change but just apply the change by using hot reloading.

Do you mean that no change are applied at all ?

**Comment by k00k** [comment]
@johnraz I realize this issue is a few months old, but I just was having the same issue so I cloned the simple project that @timcash referenced. Indeed when making a change in either `index.html` or `lib/main.js` jspm-server detects the change but does not apply the change to the DOM.

**Comment by k00k** [comment]
Hi @johnraz and @timcash - just a follow-up to my last post, I figured out the problem(s) with @timcash's  test code. Couple things to fix and it will work properly:
- Line 44 of `lib/main.js` has a spelling error and should be: `export let __hotReload = true;`
- `index.html` needs open and closing `<html>` and `</html>` tags

I think that's all I edited and then live reloading worked.

**Comment by timcash** [comment]
Ah thanks !
