### ISSUE TITLE
Future of this project ? 

### ISSUE THREAD

**Issue by johnraz** [geelen/jspm-server#31]
I would like to raise a discussion about the future of this project and wether we should intend / expect to make it more stable.

I really would like to invest some time in making this the default dev server for jspm, the same way webpack has its webpack-dev-server.

Some quick notes I've been taking regarding what should be improved in my opinion to reach a decent usable state:
- Cleanup the use of systemJS.
- Tests: I have been playing a bit with selenium today to be able to test a running jspm-server and so far I was able to test jspm-server from a browser point of view but it is still unclear how to correctly observe the hot reloading behavior. I think the problem is with the websocket, but it's just a wild guess. Maybe we should focus more on pure unit tests if this can't be achieved.
- jspm / systemjs version requirements: this should be clearly expressed in the doc.
- release notes
- Keep track of github issues and PR.
- Keep the documentation up to date and improve it when needed.

What I plan to do:
- I think having #27 finalized and merged would be nice.
- I will keep looking at improving tests.
- I will then improve the project whenever I need improvements for my personnal projects.
  (eg: I'm interested in getting jsx hot reloading back in shape)
- Contribute the best I can to answer people questions and review pull requests.

Now and before taking any further commitment I would like to take the mood of the people around the project and have a bit of feedback.

@geelen sorry to ping you again but I think you are probably the most interested in this ;-)

**Comment by MTyson** [comment]
I wonder if the lack of reply to this question indicates a temporary lull in activity, or a permanent abandonment indicating folks should not be building on top of jspm-server.

btw, I fully agree with "I really would like to invest some time in making this the default dev server for jspm, the same way webpack has its webpack-dev-server." @johnraz

**Comment by johnraz** [comment]
You should probably look here: https://github.com/capaj/systemjs-hot-reloader

I kinda gave up on this one ;-)

**Comment by MTyson** [comment]
hm, looks promising for HMR-style support, but isn't a one-stop dev server... What do you recommend for a dev-server with JSPM?

**Comment by johnraz** [comment]
I recommend you check the project more in depth along with its dependencies. You can have the exact same feature as with this project.
